### ISSUE TITLE
Chinese IME glitches when creating tags

### ISSUE THREAD

**Issue by jerrylususu** [osmoscraft/osmosmemo#6]
When I try to create a tag in Chinese, it seems that intermediate results (created by the IME) will be captured. It's basically impossible to create Chinese tags besides first type it somewhere else then copy back in.
![image](https://user-images.githubusercontent.com/17522475/119919027-3c133200-bf72-11eb-884f-7062e42db5d8.png)

The issue seems to be caused by the usage of `keydown` event, which failed to correctly handle the composition string created by IME. Probably `CompositionEvent` is the right choice.

**Comment by chuanqisun** [comment]
#7 addressed this issue. The fix is released as 2.3.0, and is live in Firefox, but may take up to a week for Edge to pick up. I screwed up the Chrome Store release (accidentally released the same old version again) and system won't let me cancel. So it would take up to 6 days for Chrome to get my actually latest release. Sorry for the delay.

谢谢！
